# Generated by Django 4.2.1 on 2023-05-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0004_alter_p_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_info',
            name='image',
            field=models.ImageField(default='default/default.jpg', max_length=50, upload_to='p_info/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
