# Generated by Django 4.2.1 on 2023-06-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0005_alter_p_info_image_alter_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='prof',
        ),
    ]
